name: Build Homebrew Bottles

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, ubuntu-latest]  # macOS 12 = Intel Ventura, Ubuntu for Linux
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Tap the Repository
        run: brew tap fane1824/tap-nightly

      - name: Install and Build Bottle
        run: |
          brew install --build-bottle fane1824/tap-nightly/lttoolbox
          brew bottle --verbose --json fane1824/tap-nightly/lttoolbox

      - name: Upload Bottles
        uses: actions/upload-artifact@v4
        with:
          name: bottles
          path: "*.bottle.tar.gz"
